// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoApp.Context;

#nullable disable

namespace ToDoApp.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220605124737_init-database")]
    partial class initdatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToDoApp.Models.Entities.TodoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpectedCompletionTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Todo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6420c9f3-d708-46c6-b278-5b4186ba1054"),
                            Created = new DateTime(2022, 6, 5, 12, 47, 36, 696, DateTimeKind.Utc).AddTicks(683),
                            Description = "None",
                            IsCompleted = 0,
                            Name = "Learn TypeScript",
                            Status = 0,
                            Updated = new DateTime(2022, 6, 5, 12, 47, 36, 696, DateTimeKind.Utc).AddTicks(685)
                        },
                        new
                        {
                            Id = new Guid("beb014b1-ac25-4a85-9544-2a31ed1b53ab"),
                            Created = new DateTime(2022, 6, 5, 12, 47, 36, 696, DateTimeKind.Utc).AddTicks(691),
                            Description = "",
                            IsCompleted = 0,
                            Name = "Learn GraphQL",
                            Status = 0,
                            Updated = new DateTime(2022, 6, 5, 12, 47, 36, 696, DateTimeKind.Utc).AddTicks(692)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
